### ISSUE TITLE
4.26 Build Tools Failed on IOS even though disabled?

### ISSUE THREAD

**Issue by Cambo-Au** [ryanjon2040/UE4-Binary-Builder#32]
Hi,

Getting a strange issue where the Build Tools CS section is failing due to files missing for IOS, even though I have IOS disabled in the build platforms. The error below is referencing a missing icon for IOS, but even working around this leads to other errors in the IOS build. Is there a way to skip this?

>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "BouncyCastle.Crypto". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\Unreal Engine 4\Builds\UnrealEngine-4.26Toon\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\iPhonePackager.csproj]
  D:\Unreal Engine 4\Builds\UnrealEngine-4.26Toon\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\Properties\Resources.resx(123,5): error MSB3103: Invalid Resx file. Could not find file 'D:\Unreal Engine 4\Builds\UnrealEngine-4.26Toon\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\Resources\GreyCheck.png'. Line 123, position 5. [D:\Unreal Engine 4\Builds\UnrealEngine-4.26Toon\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\iPhonePackager.csproj]
Took 0.6851679s to run MSBuild.exe, ExitCode=1
Command failed (Result:1): C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe "D:\Unreal Engine 4\Builds\UnrealEngine-4.26Toon\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\iPhonePackager.csproj" /property:Platform=AnyCPU /property:Configuration=Development /verbosity:minimal /target:Rebuild /verbosity:minimal /nologo. See logfile for details: 'MSBuild-2021.03.16-13.31.56.txt'
AutomationTool exiting with ExitCode=1 (Error_Unknown)
AutomationToolLauncher exited with code 0

**Comment by ryanjon2040** [comment]
Hi @Cambo-Au 

This is an issue with the Engine build itself because the app is simply passing the arguments to `AutomationTool` and running it. Not sure if this is related to #30. I have recently compiled the Engine from master branch and it was success but I don't have `iTunes` installed (required for remote building according to the [docs](https://docs.unrealengine.com/en-US/SharingAndReleasing/Mobile/iOS/Windows/index.html)). Do you have iTunes installed? If you have, maybe the Engine is trying to build iOS under the hood.
